version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # <--- IMPORTANT
    ports:
      - "9200:9200"
    networks:
      - siemnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false   # <--- IMPORTANT
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - siemnet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - siemnet

networks:
  siemnet:
    driver: bridge

 
